#!/usr/bin/env bash
set -euo pipefail

unset APPDIR APPIMAGE ARGV0 ELECTRON_RUN_AS_NODE

appimage="$HOME/Applications/T3-Code-0.0.27-x86_64.AppImage"

exec /usr/bin/zsh -lic 'exec "$@"' t3-code "$appimage" "$@"

# this has to go in .zshrc in the very beginning, otherwise it won't work
# if [[ -n "${APPIMAGE:-}" && "$APPIMAGE" == *T3-Code* ]]; then
#  echo $APPIMAGE $APPDIR $ARGV0 $ELECTRON_RUN_AS_NODE
#fi
